### ISSUE TITLE
add RBAC support

### ISSUE THREAD

**Issue by trentm** [joyent/python-manta#25]
See envvar and naming suggestions for node-manta in MANTA-2401 and follow suit: MANTA_USER, MANTA_SUBUSER.

**Comment by tgross** [comment]
@trentm looking into this is what caused me to find the issues in https://github.com/joyent/python-manta/pull/34.

I'm going to need to support this for the [`triton-mysql` blueprint](https://github.com/tgross/triton-mysql/tree/working) to do automated backups to Manta without handing over the keys to the kingdom. So unless you've got any objections, I'm going to knock this issue out as well.

**Comment by trentm** [comment]
@tgross No objections at all. Happy to CR.

**Comment by tgross** [comment]
This was merged in, should we close this issue?

**Comment by trentm** [comment]
Yup, thanks.
