### ISSUE TITLE
Paramiko added Python 3.2+ support in v 1.5.0

### ISSUE THREAD

**Issue by huxley** [joyent/python-manta#28]
Saw in the Current Status for the ReadMe that:

"Python 3 is not currently supported (currently because the dependency paramiko does not work with Python 3)."

Just FYI, Paramiko added support for Python 2.6-2.7 and 3.2+ in version 1.15.0:

https://pypi.python.org/pypi/paramiko/1.15.0

https://github.com/paramiko/paramiko/issues/16

**Comment by bryson** [comment]
Up to 3.3 now.

**Comment by hypoalex** [comment]
Random +1, Python 3 support would be great (I know, submit a PR :).

**Comment by deserat** [comment]
If you are still interested in Python 3 please see https://github.com/joyent/python-manta/tree/feature/python3.   I just got all tests passing, but would like to see it it tested in some real world scenarios before we cut an official release.

**Comment by trentm** [comment]
@deserat I see one difference at least. With this branch (and using python2, on Mac), the `mantash` prompt isn't respecting the `MANTASH_PS1` envvar:

```
$ set | grep ^MANTASH
MANTASH_PS1='[\u@\h \w]$ '

[21:58:49 trentm@danger0:~/joy/python-manta (master)]
$ git checkout feature/python3
Switched to branch 'feature/python3'
Your branch is up-to-date with 'origin/feature/python3'.

[21:59:02 trentm@danger0:~/joy/python-manta (feature/python3)]
$ mantash
mantash>
```

vs. this on "master":

```
[22:00:49 trentm@danger0:~/joy/python-manta (feature/python3)]
$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
[22:01:09 trentm@danger0:~/joy/python-manta (master)]
$ mantash
[trent.mick@us-east /trent.mick/stor]$
```

**Comment by trentm** [comment]
I'll use this branch with my mantash usage for a while -- likely with Python 2.x (currently Python 2.7.10) to test it out.

**Comment by trentm** [comment]
@deserat Still debugging prints in this branch:

```
mantash> find test_mantaclient/
Printing path  ################################
test_mantaclient/
Printing path  ################################
test_mantaclient//manyfiles
Printing path  ################################
test_mantaclient//manyfiles/f00143
...
```

makes it harder to use for testing.

**Comment by deserat** [comment]
TKS.  Will jump on print statements presently. Thought I got all those out. Even putting 'em in made me feel dirty. :)

**Comment by deserat** [comment]
I've been using this for a few weeks now. And for our limited use mantash and python api functions seem to be working ok.   Before cutting a release, does anybody have feedback?

**Comment by trentm** [comment]
@deserat It seems that on the 'feature/python3' branch, the `MANTASH_PS1` envvar isn't being properly used?

```
[14:34:53 trentm@danger0:~/joy/python-manta (master)]
$ mantash
[trent.mick@us-east /trent.mick/stor]$ ^D
[14:35:03 trentm@danger0:~/joy/python-manta (master)]
$ git checkout feature/python3
Switched to branch 'feature/python3'
Your branch is up-to-date with 'origin/feature/python3'.
[14:35:08 trentm@danger0:~/joy/python-manta (feature/python3)]
$ mantash
mantash>
```

This is using Python 2.7.1 on Mac if that matters.

**Comment by rjloura** [comment]
Closing as we have #8 open for py3 support.
