### ISSUE TITLE
Open to a transfer of the PyPI package name `manta`?

### ISSUE THREAD

**Issue by fischermoseley** [joyent/python-manta#64]
Hello! I'm the author of [another Python package named after a marine animal](https://github.com/fischermoseley/manta), and I wanted to ask if the maintainers (@trentm?) of this repo would be open to a transfer of the PyPI package name. I was hoping to publish my package under the name `manta` on PyPI, which would replace this package with mine on the PyPI registry. 

It looks like there's still some download traffic of this package from PyPI, but I'm not sure what portion of that is from users versus bots:

https://pypistats.org/packages/manta

Since my package is new and not yet published to PyPI, I don't have any existing workloads that are dependent on the name and can publish under a different name. However, having the name `manta` would be extraordinarily convenient for folks using my project! I don't want to break anything for your users, however it seems like it's been a few years since this repo has seen activity, so I could see the possibility of that being small.

In either case, thank you for the consideration!
-Fischer

**Comment by bahamat** [comment]
Hi @fischermoseley,

Thanks for reaching out. As it turns out, Manta is still an actively maintained and used product, including the python module. It's not something we can or are willing to transfer.
