### ISSUE TITLE
get pip install working (with requirements.txt)

### ISSUE THREAD

**Issue by trentm** [joyent/python-manta#7]
Get this working:

```
pip install git+https://github.com/joyent/python-manta.git#egg=manta
```

**Comment by deserat** [comment]
This works for python 2.  It currently works on my test system for python 3 but I need to validate with a clean system.

sudo pip3  install git+https://github.com/joyent/python-manta@feature/python3#egg=manta --upgrade

**Comment by deserat** [comment]
pip install now works for python3 in the feature/python3 branch if appropriate requirements are installed.  Not sure if you were hoping for a fully baked wheel install but I think  that would involve ensuring this project tracks openssl, crypto, and paramiko vulnerabilities and I don't feel comfortable doing that.  Thoughts?

**Comment by trentm** [comment]
@deserat I don't have a current need for the original ticket description. I don't recall the original motivation. TBH I don't know anything about "wheels".  I'm happy dropping this ticket, if that is what you are asking.

**Comment by tgross** [comment]
> TBH I don't know anything about "wheels". 

Wheels are the "new" (and optional) package format which includes pre-compiled libraries anywhere there's a C extension. `pip` will try to find wheels on PyPI first, and then fallback to pulling the source package (tarball) normally.

**Comment by deserat** [comment]
Closing issues as c extensions are in the dependencies crypto and paramkio. pip install works if dependencies are installed or installable.
